[workspace]
members = ["crates/*"]
resolver = "2"

[package]
name = "zapret-rust"
version = "2.2.0"
edition = "2021"
license = "MIT"
description = "Zapret-Rust TUI implementation for DPI bypass"
repository = "https://github.com/Sergeydigl3/zapret-discord-youtube-rust"

[dependencies]
zapret-core = { path = "crates/zapret-core" }
zapret-fetch = { path = "crates/zapret-fetch" }
zapret-tui = { path = "crates/zapret-tui" }
zapret-wrapper = { path = "crates/zapret-wrapper" }
clap = { version = "4.4", features = ["derive"] }
inquire = "0.6"
ctrlc = "3.4"
nix = { version = "0.27", features = ["signal", "user"] }
rust-i18n = "4.1.0"
sys-locale = "0.3.2"

[target.'cfg(target_os = "windows")'.dependencies]
windows-service = "0.6.0"

[[bin]]
name = "zapret-rust"
path = "src/main.rs"
