[target.x86_64-unknown-linux-gnu]
linker = "cc"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[profile.dev]
incremental = true
codegen-units = 256
lto = "off"

[profile.release]
incremental = true
codegen-units = 1
lto = "thin"
strip = "symbols"
